# Generated by Django 3.0 on 2020-11-24 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_create_bus_and_pencatatan_bus'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pencatatanbus',
            name='asal_tujuan_trayek',
        ),
        migrations.AddField(
            model_name='bus',
            name='asal_tujuan_trayek',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
    ]
