# Generated by Django 3.0 on 2020-12-14 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20201124_1625'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bus',
            name='jenis_trayek',
            field=models.CharField(choices=[('AKAP', 'AKAP'), ('AKDP', 'AKDP'), ('ANGKT', 'ANGKT')], max_length=5),
        ),
        migrations.AlterField(
            model_name='pencatatanbus',
            name='jenis',
            field=models.CharField(choices=[('BT', 'BT'), ('TB', 'TB')], max_length=2),
        ),
        migrations.AlterField(
            model_name='pencatatanbus',
            name='keterangan',
            field=models.CharField(choices=[('LINTAS', 'LINTAS'), ('BERANGKAT', 'BERANGKAT'), ('TIBA', 'TIBA')], max_length=10),
        ),
        migrations.AlterModelTable(
            name='bus',
            table='app_bus',
        ),
    ]
